test report

diff --git a/.github/workflows/integrate.yml b/.github/workflows/integrate.yml
--- a/.github/workflows/integrate.yml
+++ b/.github/workflows/integrate.yml
@@ -27,5 +27,12 @@ jobs:
         run: ls -alR -I .git -I node_modules -I .vscode -I .github
       - name: run tests
         run: npm run test
-      - name: build
-        run: npm run build
+      # - name: build
+      # run: npm run build
+      - name: test report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: JEST Tests # Name of the check run which will be created
+          path: reports/jest-*.xml # Path to test results
+          reporter: jest-junit # Format of test results
